#!/bin/bash

# Download function for ease of reuse
function install_autojump{
  echo_message info 'Installing '$NAME'...'
  wget -nc https://github.com/downloads/joelthelion/autojump/autojump_v21.1.2.tar.gz
  tar -xzvf autojump_v21.1.2.tar.gz
  cd autojump_v21.1.2
  ./install.sh

  # clean
  cd ..
  rm -rf autojump_v21.1.2
  rm -rf autojump_v21.1.2.tar.gz
  echo_message success "Installation of '$PACKAGE' complete."
}

function autojump{
  # Variables
  NAME="autojump"
  PACKAGE=j
  # Install
  echo_message header 'Begin '$NAME' installation'
  # Check if package is installed
  check_packages $PACKAGE
  exitstatus=$?
  # If package is not installed
  if [ $exitstatus = 1 ]; then
    echo_message info $NAME 'is not installed.'
    echo 'Proceeding'
    install_autojump
    whiptail --title "Finished" --msgbox "Installation $NAME complete." 8 64
  else
    # Already installed
    echo_message $NAME 'already installed.'
    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
  fi
  thirdparty_packages
}
