#!/bin/bash

# Download function for ease of reuse
function install_cmake {
  echo_message info 'Downloading '$NAME'...'
  curl -O https://codeload.github.com/Kitware/CMake/zip/master
  # Install package(s)
  echo_message info 'Installing '$NAME'...'
  unzip master
  cd CMake-master
  ./bootstrap --prefix=/usr/local && make
  elevate_privilege "make install"

  # Cleanup and finish
  cd .. # back to the top directory
  rm -rf master
  rm -rf CMake-master
  echo_message success "Installation of '$PACKAGE' complete."
}

# install git using the tar.gz
function cmake {
  # Variables
  NAME="cmake"
  PACKAGE=cmake
  # Install
  echo_message header 'Begin '$NAME' installation'
  # Check if package is installed
  check_packages $PACKAGE
  exitstatus=$?
  # If package is not installed
  if [ $exitstatus = 1 ]; then
    echo_message info $NAME 'is not installed.'
    echo 'Proceeding'
    install_cmake
    whiptail --title "Finished" --msgbox "Installation $NAME complete." 8 64
  else
    # Already installed
    echo_message info $NAME 'already installed.'
    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
  fi
  thirdparty_packages
}
