#!/bin/bash

function install_feishu {
  echo_message info 'Downloading '$NAME'...'

  wget -nc https://lf6-ug-sign.feishucdn.com/ee-appcenter/018b8d40/Feishu-linux_x64-7.28.10.deb?lk3s=fb957577&x-expires=1734851675&x-signature=zbQ6WffsWFHH9YkzloGcNhzIsr8%3D -O feishu.deb

  # Install package(s)
  echo_message info 'Installing '$NAME'...'
  elevate_privilege "gdebi feishu.deb"

  # Cleanup and finish
  rm -rf feishu.deb
  echo_message success "Installation of '$PACKAGE' complete."
}

function feishu {
  # Variables
  NAME="feishu"
  PACKAGE=feishu
  # Install
  echo_message header 'Begin '$NAME' installation'
  # Check if package is installed
  check_packages $PACKAGE
  exitstatus=$?
  # If package is not installed
  if [ $exitstatus = 1 ]; then
    echo_message info $NAME 'is not installed.'
    echo 'Proceeding'
    install_feishu
    whiptail --title "Finished" --msgbox "Installation $NAME complete." 8 64
  else
    # Already installed
    echo_message info $NAME 'already installed.'
    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
  fi
  thirdparty_packages
}
