#!/bin/bash

# Download function for ease of reuse
function install_fzf{
  echo_message info 'Installing '$NAME'...'
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install
  echo_message success "Installation of '$PACKAGE' complete."
}

function fzf{
  # Variables
  NAME="fzf"
  PACKAGE=fzf
  # Install
  echo_message header 'Begin '$NAME' installation'
  # Check if package is installed
  exitstatus=1 #not exit
  if[ ! -d ~/bxgithub/.fzf]; then
    exitstatus=0
  fi
  # If package is not installed
  if [ $exitstatus = 1 ]; then
    echo_message info $NAME 'is not installed.'
    echo 'Proceeding'
    install_fzf
    whiptail --title "Finished" --msgbox "Installation $NAME complete." 8 64
  else
    # Already installed
    echo_message $NAME 'already installed.'
    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
  fi
  thirdparty_packages
}
