#!/bin/bash

# Download function for ease of reuse
function install_git {
  echo_message info 'Downloading '$NAME'...'
  curl -O https://codeload.github.com/git/git/zip/master
  # Install package(s)
  echo_message info 'Installing '$NAME'...'
  elevate_privilege "apt-get install -fy zlib1g-dev"
  unzip master
  cd git-mater
  make prefix=/usr/local all doc info
  elevate_privilege "make prefix=/usr/local install install-doc install-html install-info"
  # elevate_privilege "make install"

  # Cleanup and finish
  cd .. # back to the top directory
  rm -rf master
  rm -rf git-master

  echo_message info 'Configure '$NAME'...'
  git config --global user.email "baoxianzhit@gmail.com"
  git config --global user.name "baoxianzhang"
  git config --global core.editor vim
  git config --global push.default simple
  git config --global alias.unstage "reset HEAD --"
  git config --global alias.last "log -1 HEAD"

  echo_message success "Installation of '$PACKAGE' complete."
}

# install git using the tar.gz
function git {
  # Variables
  NAME="git"
  PACKAGE=git
  # Install
  echo_message header 'Begin '$NAME' installation'
  # Check if package is installed
  # check_packages $PACKAGE
  # exitstatus=$?
  
  exitstatus=1  # default is not install
  # If package is not installed
  if [ $exitstatus = 1 ]; then
    echo_message info $NAME 'is not installed.'
    echo 'Proceeding'
    install_git
    whiptail --title "Finished" --msgbox "Installation $NAME complete." 8 64
  else
    # Already installed
    echo_message $NAME 'already installed.'
    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
  fi
  thirdparty_packages
}
