#!/bin/bash

# Download function for ease of reuse
function install_git {
  echo_message info 'Add lastest '$NAME' ppa ...'
  elevate_privilege "add-apt-repository ppa:git-core/ppa"
  elevate_privilege "apt update"
  elevate_privilege "apt install git -y"

#  echo_message info 'Configure '$NAME'...'
#  git config --global user.email "baoxianzhit@gmail.com"
#  git config --global user.name "baoxianzhang"
#  git config --global core.editor vim
#  git config --global push.default simple
#  git config --global alias.unstage "reset HEAD --"
#  git config --global alias.last "log -1 HEAD"

  echo_message success "Installation of '$PACKAGE' complete."
}

function latest_git {
  # Variables
  NAME="git"
  PACKAGE=git
  # Install
  echo_message header 'Begin '$NAME' installation'
  # Check if package is installed
  # check_packages $PACKAGE
  # exitstatus=$?
  
  exitstatus=1  # default is not install
  # If package is not installed
  if [ $exitstatus = 1 ]; then
    echo_message info $NAME 'is not installed.'
    echo 'Proceeding'
    install_git
    whiptail --title "Finished" --msgbox "Installation $NAME complete." 8 64
  else
    # Already installed
    echo_message $NAME 'already installed.'
    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
  fi
  thirdparty_packages
}
