#!/bin/bash

# Download function for ease of reuse
function install_gtag {
  echo_message info 'Installing '$NAME'...'
  wget -nc http://tamacom.com/global/global-6.5.5.tar.gz
  tar -xzvf global-6.5.5.tar.gz
  cd global-6.5.5
  elvate_privilege "apt-get install -y libsdl1.2-dev"
  elvate_privilege "apt-get install -y ncurses-bin"
  elvate_privilege "apt-get install -y libncurses5-dev"
  ./configure
  make
  elvate_privilege "make install"
  # clean
  cd ..
  rm global-6.5.5 -rf
  rm global-6.5.5.tar.gz
  echo_message success "Installation of '$PACKAGE' complete."
}

function gtag {
  # Variables
  NAME="gtag"
  PACKAGE=gtag
  # Install
  echo_message header 'Begin '$NAME' installation'
  # Check if package is installed
  check_packages $PACKAGE
  exitstatus=$?
  # If package is not installed
  if [ $exitstatus = 1 ]; then
    echo_message info $NAME 'is not installed.'
    echo 'Proceeding'
    install_gtag
    whiptail --title "Finished" --msgbox "Installation $NAME complete." 8 64
  else
    # Already installed
    echo_message $NAME 'already installed.'
    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
  fi
  thirdparty_packages
}
