#!/bin/bash

# Download function for ease of reuse
function install_latex() {
  echo_message info 'Installing '$NAME'...'
  elevate_privilege "apt-get install texlive-full"
  elevate_privilege "apt-get install texmaker"
  elevate_privilege "apt-get install latex-cjk-all"
  echo_message success "Installation of '$PACKAGE' complete."
}

function latex() {
  # Variables
  NAME="latex"
  PACKAGE=latex 
  # Install
  echo_message header 'Begin '$NAME' installation'
  # Check if package is installed
  exitstatus=1 #not exit

  # If package is not installed
  if [ $exitstatus = 1 ] ; then
    echo_message info $NAME 'is not installed.'
    echo 'Proceeding'
    install_latex
    whiptail --title "Finished" --msgbox "Installation $NAME complete." 8 64
  else
    # Already installed
    echo_message $NAME 'already installed.'
    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
  fi
  thirdparty_packages
}
