#!/bin/bash

# Download function for ease of reuse

function install_myfile {
  echo_message info 'Downloading '$NAME'...'
  mkdir -p $HOME/bxgithub
  cd $HOME/bxgithub
  git clone https://github.com/baoxianzhang/myfile.git

  # softlink zsh
  rm -f $HOME/.zshrc
  ln -s $HOME/bxgithub/myfile/zshrc $HOME/.zshrc

  # spacemacs.d
  rm -rf $HOME/.spacemacs.d
  ln -s $HOME/bxgithub/myfile/spacemacs.d $HOME/.spacemacs.d

  # tmux
  rm -rf $HOME/.tmux.conf
  ln -s $HOME/bxgithub/myfile/tmux.conf $HOME/.tmux.conf

  # spf13 vim
  rm -rf $HOME/.vimrc.before.local
  ln -s $HOME/bxgithub/myfile/vimrc.before.local $HOME/.vimrc.before.local
  rm -rf $HOME/.vimrc.bundles.local
  ln -s $HOME/bxgithub/myfile/vimrc.bundles.local $HOME/.vimrc.bundles.local

  # git templates and projectinit
  rm -rf ~/.git-templates
  rm -rf ~/.git-clone-init
  rm -rf ~/.gitconfig
  ln -s ~/bxgithub/myfile/git-templates ~/.git-templates
  ln -s ~/bxgithub/myfile/git-templates/.git-clone-init ~/.git-clone-init
  ln -s ~/bxgithub/myfile/git-templates/.gitconfig ~/.gitconfig

  # Install package(s)
  echo_message info 'Installing '$NAME'...'
  echo_message success "Installation of '$PACKAGE' complete."
}

# install git using the tar.gz
function myfile {
  # Variables
  NAME="myfile"
  PACKAGE=myfile
  # Install
  echo_message header 'Begin '$NAME' installation'
  # Check if package is installed
  exitstatus=1
  if [ -d $HOME/bxgithub/myfile ]; then
    exitstatus=0
  fi
  # If package is not installed
  if [ $exitstatus = 1 ]; then
    echo_message info $NAME 'is not installed.'
    echo 'Proceeding'
    install_myfile
    whiptail --title "Finished" --msgbox "Installation $NAME complete." 8 64
  else
    # Already installed
    echo_message $NAME 'already installed.'
    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
  fi
  thirdparty_packages
}
