#!/bin/bash

# Download function for ease of reuse
function install_myfile {
  echo_message info 'Downloading '$NAME'...'
  mkdir -p ~/bxgithub
  cd ~/bxgithub
  git clone https://github.com/baoxianzhang/myfile.git

  # softlink zsh
  rm -f ~/.zshrc
  ln -s ~/bxgithub/myfile/zshrc ~/.zshrc

  # spacemacs.d
  rm -rf ~/.spacemacs.d
  ln -s ~/bxgithub/myfile/spacemacs.d ~/.spacemacs.d

  # tmux
  rm -rf ~/.tmux.conf
  ln -s ~/bxgithub/myfile/tmux.conf ~/.tmux.conf

  # spf13 vim
  rm -rf ~/.vimrc.before.local
  ln -s ~/bxgithub/myfile/vimrc.before.local ~/.vimrc.before.local
  rm -rf ~/.vimrc.bundles.local
  ln -s ~/bxgithub/myfile/vimrc.bundles.local ~/.vimrc.bundles.local

  # Install package(s)
  echo_message info 'Installing '$NAME'...'
  echo_message success "Installation of '$PACKAGE' complete."
}

# install git using the tar.gz
function myfile {
  # Variables
  NAME="myfile"
  PACKAGE=myfile
  # Install
  echo_message header 'Begin '$NAME' installation'
  # Check if package is installed
  exitstatus=1 #not exit
  if[ ! -d ~/bxgithub/myfile ]; then
    exitstatus=0
  fi
  # If package is not installed
  if [ $exitstatus = 1 ]; then
    echo_message info $NAME 'is not installed.'
    echo 'Proceeding'
    install_myfile
    whiptail --title "Finished" --msgbox "Installation $NAME complete." 8 64
  else
    # Already installed
    echo_message $NAME 'already installed.'
    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
  fi
  thirdparty_packages
}
