#!/bin/bash

# Download function for ease of reuse
function install_nutstore() {
	echo_message info 'Installing '$NAME'...'
  wget -c https://www.jianguoyun.com/static/exe/installer/ubuntu/nautilus_nutstore_amd64.deb
  elvate_privilege "dpkg -i nautilus_nutstore_amd64.deb"
  elvate_privilege "apt-get install -f"

  # clean
  # rm nautilus_nutstore_amd64.deb -rf
  echo_message success "Installation of '$PACKAGE' complete."
}

function nutstore() {
  # Variables
  NAME="nutstore"
  PACKAGE=nutstore
  # Install
  echo_message header 'Begin '$NAME' installation'
  # Check if package is installed
  check_packages $PACKAGE
  exitstatus=$?
  # If package is not installed
  if [ $exitstatus = 1 ]; then
    echo_message info $NAME 'is not installed.'
    echo 'Proceeding'
    install_nutstore
    whiptail --title "Finished" --msgbox "Installation $NAME complete." 8 64
  else
    # Already installed
    echo_message $NAME 'already installed.'
    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
  fi
  thirdparty_packages
}
