#!/bin/bash

# Download function for ease of reuse
function install_shadowsocks() {
  elevate_privilege "apt-get install -y python-pip"
  elevate_privilege "pip install --upgrade git+https://github.com/shadowsocks/shadowsocks.git@master"
  wget -O libsodium.tar.gz -nc https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
  tar xvf libsodium.tar.gz && cd libsodium-stable && ./configure --prefix=/usr && make && sudo make install
  # elevate_privilege "apt-get install -y polipo"
  # sudo cp ${CONFIGDIR}/polipo.conf /etc/polipo/config
  # elevate_privilege "service polipo stop"
  # elevate_privilege "service polipo start"

  cd ../
  rm libsodium-stable -rf

  echo_message success "Installation of '$PACKAGE' complete."
}

function shadowsocks() {
  # Variables
  NAME="shadowsock"
  PACKAGE=shadowsock
  # Install
  echo_message header 'Begin '$NAME' installation'
  # Check if package is installed
  # check_packages $PACKAGE
  # exitstatus=$?
  
  exitstatus=1  # default is not install
  # If package is not installed
  if [ $exitstatus = 1 ]; then
    echo_message info $NAME 'is not installed.'
    echo 'Proceeding'
    install_shadowsocks
    whiptail --title "Finished" --msgbox "Installation $NAME complete." 8 64
  else
    # Already installed
    echo_message $NAME 'already installed.'
    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
  fi
  thirdparty_packages
}
