#!/bin/bash

function install_sogou {
  echo_message info 'Downloading '$NAME'...'
  elevate_privilege 'apt-get install fcitx -y'
  elevate_privilege 'apt-get -f install'
  sudo apt-get -f install
  wget -O sogoupinyin_amd64.deb http://cdn2.ime.sogou.com/dl/index/1509619794/sogoupinyin_2.2.0.0102_amd64.deb\?st\=MSv-W3DzFHp2LKX-AzRtAw\&e\=1516781430\&fn\=sogoupinyin_2.2.0.0102_amd64.deb
  # Install package(s)
  echo_message info 'Installing '$NAME'...'
  # elevate_privilege "dpkg -i sogoupinyin_amd64.deb"
  elevate_privilege "gdebi sogoupinyin_amd64.deb"
  # Cleanup and finish
  # rm -rf sogoupinyin_amd64.deb
  echo_message success "Installation of '$PACKAGE' complete."
}

function sogou {
  # Variables
  NAME="sogou"
  PACKAGE=sogou
  # Install
  echo_message header 'Begin '$NAME' installation'
  # Check if package is installed
  # check_packages $PACKAGE
  # exitstatus=$?
  exitstatus=1
  # If package is not installed
  if [ $exitstatus = 1 ]; then
    echo_message info $NAME 'is not installed.'
    echo 'Proceeding'
    install_sogou
    whiptail --title "Finished" --msgbox "Installation $NAME complete." 8 64
  else
    # Already installed
    echo_message info $NAME 'already installed.'
    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
  fi
  thirdparty_packages
}
