#!/bin/bash

# Download function for ease of reuse
function install_spacemacs() {
  THIS_DIR=$(pwd)
  echo_message info 'Downloading '$NAME'...'
  EMACS_VERSION=emacs-26.3
  wget -nc http://mirrors.ustc.edu.cn/gnu/emacs/${EMACS_VERSION}.tar.gz
  tar -xzvf ${EMACS_VERSION}.tar.gz
  cd ${EMACS_VERSION}
  elevate_privilege "apt-get install -y libgtk2.0-dev"
  elevate_privilege "apt-get install -y libxpm-dev"
  elevate_privilege "apt-get install -y libncurses5-dev"
  elevate_privilege "apt-get install -y libjpeg-dev"
  elevate_privilege "apt-get install -y libgif-dev"
  elevate_privilege "apt-get install -y libtiff5-dev"
  elevate_privilege "apt-get install -y gnutls-dev"
  ./configure
  make
  elevate_privilege "make install"

  # clean
  cd ..
  rm ${EMACS_VERSION} -rf
  # rm ${EMACS_VERSION}.tar.gz

  mkdir -p ~/bxgithub
  cd ~/bxgithub
  git clone https://github.com/syl20bnr/spacemacs.git
  cd spacemacs
  git checkout develop
  rm -rf ~/.emacs.d
  ln -s ~/bxgithub/spacemacs ~/.emacs.d
  ln -s ~/bxgithub/myfile/spacemacs.d ~/.spacemacs.d

  # install tern
  elevate_privilege "apt-get install -y npm"
  elevate_privilege "npm install -g tern"

  # install source-code-pro
  wget -c https://www.fontsquirrel.com/fonts/download/source-code-pro
  FONT_PATH=/usr/share/fonts/opentype
  elevate_privilege "mkdir $FONT_PATH"
  elevate_privilege  "unzip source-code-pro -d $FONT_PATH"
  cd $FONT_PATH
  elevate_privilege "fc-cache -f -v"
  cd ${THIS_DIR}

  # Install package(s)
  echo_message info 'Installing '$NAME'...'
  echo_message success "Installation of '$PACKAGE' complete."
}

# install git using the tar.gz
function spacemacs() {
  # Variables
  NAME="spacemacs"
  PACKAGE=spacemacs
  # Install
  echo_message header 'Begin '$NAME' installation'
  # Check if package is installed
  check_packages $PACKAGE
  exitstatus=$?
  # If package is not installed
  if [ $exitstatus = 1 ]; then
    echo_message info $NAME 'is not installed.'
    echo 'Proceeding'
    install_spacemacs
    whiptail --title "Finished" --msgbox "Installation $NAME complete." 8 64
  else
    # Already installed
    echo_message $NAME 'already installed.'
    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
  fi
  thirdparty_packages
}
