#!/bin/bash

function install_wechat {
  echo_message info 'Downloading '$NAME'...'

  wget -nc https://dldir1v6.qq.com/weixin/Universal/Linux/WeChatLinux_x86_64.deb -O WeChatLinux_x86_64.deb

  # Install package(s)
  echo_message info 'Installing '$NAME'...'
  elevate_privilege "gdebi WeChatLinux_x86_64.deb"

  # Cleanup and finish
  rm -rf WeChatLinux_x86_64.deb
  echo_message success "Installation of '$PACKAGE' complete."
}

function wechat {
  # Variables
  NAME="wechat"
  PACKAGE=wechat
  # Install
  echo_message header 'Begin '$NAME' installation'
  # Check if package is installed
  check_packages $PACKAGE
  exitstatus=$?
  # If package is not installed
  if [ $exitstatus = 1 ]; then
    echo_message info $NAME 'is not installed.'
    echo 'Proceeding'
    install_wechat
    whiptail --title "Finished" --msgbox "Installation $NAME complete." 8 64
  else
    # Already installed
    echo_message info $NAME 'already installed.'
    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
  fi
  thirdparty_packages
}
