#!/bin/bash

function install_wps {
  echo_message info 'Not work yet'
  # echo_message info 'Downloading '$NAME'...'

  # wget -c http://kdl.cc.ksosoft.com/wps-community/download/a21/wps-office_10.1.0.5672~a21_amd64.deb -O wps-office_amd64.deb

  # Install package(s)
  # echo_message info 'Installing '$NAME'...'
  # elevate_privilege "dpkg -i wps-office_amd64.deb"

  # Cleanup and finish
  # rm -rf wps-office_amd64.deb
  echo_message success "Installation of '$PACKAGE' complete."
}

function wps {
  # Variables
  NAME="wps"
  PACKAGE=wps
  # Install
  echo_message header 'Begin '$NAME' installation'
  # Check if package is installed
  check_packages $PACKAGE
  exitstatus=$?
  # If package is not installed
  if [ $exitstatus = 1 ]; then
    echo_message info $NAME 'is not installed.'
    echo 'Proceeding'
    install_wps
    whiptail --title "Finished" --msgbox "Installation $NAME complete." 8 64
  else
    # Already installed
    echo_message info $NAME 'already installed.'
    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
  fi
  thirdparty_packages
}
