#!/bin/bash

# Download function for ease of reuse
function install_zotero {
	echo_message info 'Installing '$NAME'...'
  wget -c https://download.zotero.org/client/release/5.0.34/Zotero-5.0.34_linux-x86_64.tar.bz2
  tar -xf Zotero-5.0.34_linux-x86_64.tar.bz2
  cd Zotero-5.0.34_linux-x86_64

  # clean
  cd ..
  rm Zotero-5.0.34_linux-x86_64.tar.bz2 -rf
  rm Zotero-5.0.34_linux-x86_64 -rf
  echo_message success "Installation of '$PACKAGE' complete."
}

# install git using the tar.gz
function zotero {
  # Variables
  NAME="zotero"
  PACKAGE=zotero
  # Install
  echo_message header 'Begin '$NAME' installation'
  # Check if package is installed
  check_packages $PACKAGE
  exitstatus=$?
  # If package is not installed
  if [ $exitstatus = 1 ]; then
    echo_message info $NAME 'is not installed.'
    echo 'Proceeding'
    install_zotero
    whiptail --title "Finished" --msgbox "Installation $NAME complete." 8 64
  else
    # Already installed
    echo_message $NAME 'already installed.'
    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
  fi
  thirdparty_packages
}
